### PR TITLE
Make it support non-English language (like Chinese)

### PR DESCRIPTION
**Pull request by terryyin**
The "Get Json Value" api now will dump the Json part into a string. For English it's still no too inconvenient to check the value (just add the quote). But Chinese will be transformed into something like "\u8fcd". So make the dumps not ensure ascii.

### CODE REVIEW

**Comment by peritus** [comment]
Looks about right.

**Comment by peritus** [comment]
@terryyin Thank you.

There are more occurrences of `json.dumps` (for logging, etc.) — do you mind chinese-proofing those as well ?

**Comment by terryyin** [comment]
Oh, sure.

**Comment by jinlxz** [comment]
I have found the POST and Get keyworks doesn't support chinese, it will fail if the body contains chinese chars,  and how can I work around or fix this issue, can you give me some suggestion?

**Comment by terryyin** [comment]
Have you tried if it works for Python3? If yes, it's a encoding problem.

**Comment by jinlxz** [comment]
no, i am running python 2.7.2, haven't gotten a  plan to upgrade python. Truely it is a encoding problem,  the error message is  "UnicodeDecodeError: 'ascii' codec can't decode byte ..."  when the POST keyword was invoked. and I found the request body contained some non-ascii chars, I think it is a encoding problem but i am not familar with python, shall I need to modify the source code or some tricks can work around it, can you give me some more adivces?  it will be very appreciate,  thank you.

**Pull request merged**
