### PR TITLE
Https support

### PR DESCRIPTION
**Pull request by pasieronen**
Currently robotframework-httplibrary only supports plain http. Here's a patch adding basic support for https, too.

### CODE REVIEW

**Comment by peritus** [comment]
If this has tests and documentation, i'll merge it.

**Comment by peritus** [comment]
Thanks!

**Comment by pasieronen** [comment]
I've now re-generated the documentation with libdoc, and added a simple test case. The test case was a bit tricky, because Python's BaseHTTPServer does not support https out-of-the-box.

**Comment by pasieronen** [comment]
Hmm, the test cases fail on travisbot. It looks like mockserver.py fails to start, but without seeing the exception, it's hard to tell why.

One possibility would be the pyOpenSSL library, which mockserver now requires. I don't know how to best declare this as a dependency for tests only (if I don't want to add it to setup.py "install_requires" list). I'll experiment a bit with buildout.cfg..

**Comment by pasieronen** [comment]
OK, now the paths are correct for mockserver, too, and it seems to work without system-wide pyOpenSSL install.

**Pull request closed without merging**
